"""
Component Selector: decides which narrative components qualify for this week.

This is where the 'have something to say or stay silent' principle lives.
A weak signal is no signal — we don't fabricate components just to fill space.

Implicit Question is generated by the LLM (it requires creative reasoning,
not aggregation), so we only signal *whether* it should appear, not its content.
"""

from typing import Optional
import pandas as pd

from models import NarrativeComponents
from .theme_map import build_theme_map
from .theme_evolution import build_theme_evolutions
from .hidden_pattern import build_hidden_patterns
from .centerpiece import select_centerpiece
from .quiet_shift import build_quiet_shifts


# Below this note count, we consider data "sparse" and emit a simplified narrative.
SPARSE_THRESHOLD = 5


def select_components(
    df: pd.DataFrame, previous_report: Optional[dict]
) -> tuple[NarrativeComponents, bool]:
    """
    Run all aggregators and assemble selected components.

    Returns:
        (components, is_sparse)
    """
    is_sparse = len(df) < SPARSE_THRESHOLD

    if df.empty:
        return NarrativeComponents(), True

    # Always-attempted components (each aggregator decides if it has enough data)
    theme_map = build_theme_map(df, previous_report)
    centerpiece = select_centerpiece(df)

    # These require richer data - skipped silently in sparse mode
    if is_sparse:
        return (
            NarrativeComponents(
                theme_map=theme_map,
                centerpiece=centerpiece,
            ),
            is_sparse,
        )

    theme_evolutions = build_theme_evolutions(df)
    hidden_patterns = build_hidden_patterns(df)
    quiet_shifts = build_quiet_shifts(df, previous_report)

    return (
        NarrativeComponents(
            theme_map=theme_map,
            theme_evolutions=theme_evolutions,
            hidden_patterns=hidden_patterns,
            centerpiece=centerpiece,
            quiet_shifts=quiet_shifts,
            # implicit_questions left empty - the LLM generates these directly from the prompt
        ),
        is_sparse,
    )
